RekamMedik/Controllers/ReportExcelController.cs
using Newtonsoft.Json;
using OfficeOpenXml;
using RekamMedik.Entities;
using RekamMedik.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RekamMedik.Controllers
{
    public class ReportExcelController : Controller
    {
        // GET: ReportExcel
        public ActionResult Index()
        {
            var m = new ReportRLHelperViewModel();
            m.Name = "Dartar Report RL";
            m.RL_List = new List<ExcelInfoViewModel>() {
                new ExcelInfoViewModel()
                {
                    param = "RL 5.1_Pengunjung SIRS",
                },
                new ExcelInfoViewModel()
                {
                    param = "RL 5.2_Kunjungan Rawat Jalan",
                },
                new ExcelInfoViewModel()
                {
                    param = "RL 5.3 10_Besar Penyakit Rawat Inap",
                },
                new ExcelInfoViewModel()
                {
                    param = "RL 5.4 10_Besar Penyakit Rawat Jalan",
                }
            };
            return View(m);
        }

        public ActionResult DownloadReport(string name_xls, DateTime fromdate, DateTime todate)
        {
            //var s_formdate = DateTime.Parse("2022-01-01");
            //var s_todate = DateTime.Parse("2022-06-30");
            //var s_name_xls = "RL 5.1_Pengunjung SIRS";

            var exlRpt = new Configurator(name_xls, fromdate, todate);
            var declareReport = exlRpt.initiator();

            var templateFileInfo = new FileInfo(Path.Combine(Server.MapPath($"~/CrystalReports/ExcelTemp/") + declareReport.filename));
            Stream stream = new MemoryStream();
            if (templateFileInfo.Exists)
            {
                using (ExcelPackage p = new ExcelPackage(templateFileInfo))
                {
                    ExcelWorksheet wsEstimate = p.Workbook.Worksheets[declareReport.worksheet];

                    exlRpt.ExcelReport(wsEstimate);

                    p.SaveAs(stream);
                    stream.Position = 0;
                }
            }
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", declareReport.title + ".xlsx");
        }

    }

    public class Configurator{

        private string _config { get; set; }
        private DateTime _fromdate { get; set; }
        private DateTime _todate { get; set; }

        public Configurator(string config, DateTime fromdate, DateTime todate)
        {
            _config = config;
            _fromdate = fromdate;
            _todate = todate;
        }

        public ExcelInfoViewModel initiator()
        {
            var rpt = declareReport();
            var m_rpt = rpt.FirstOrDefault(x => x.param == _config);
            return m_rpt;
        }

        public ExcelWorksheet ExcelReport(ExcelWorksheet exl)
        {
            if (_config == "RL 5.1_Pengunjung SIRS")
            {
                var no = 1;
                var row = 2;
                using (var s = new SIMEntities())
                {
                    var dt = s.RL_5_1(_fromdate,_todate).ToList();
                    foreach (var x in dt)
                    {
                        //Kode_RS Nama_RS Bulan Tahun   Nama_KabKota Kode_Prov   Nomor JenisKegiatan   Jumlah
                        exl.Cells[$"A{row}"].Value = x.Kode_RS;
                        exl.Cells[$"B{row}"].Value = x.Nama_RS;
                        exl.Cells[$"C{row}"].Value = x.Bulan;
                        exl.Cells[$"D{row}"].Value = x.Tahun;
                        exl.Cells[$"E{row}"].Value = x.Nama_KabKota;
                        exl.Cells[$"F{row}"].Value = x.Kode_Prov;
                        exl.Cells[$"G{row}"].Value = x.Nomor;
                        exl.Cells[$"H{row}"].Value = x.JenisKegiatan;
                        exl.Cells[$"I{row}"].Value = x.Jumlah;

                        no++;
                        row++;
                    }
                }
            }
            else if(_config == "RL 5.2_Kunjungan Rawat Jalan")
            {
                var no = 1;
                var row = 2;
                using (var s = new SIMEntities())
                {
                    var dt = s.RL_5_2(_fromdate, _todate).ToList();
                    foreach (var x in dt)
                    {
                        //Kode_RS Nama_RS Bulan Tahun   Nama_KabKota Kode_Prov   Nomor JenisKegiatan   JML
                        exl.Cells[$"A{row}"].Value = x.Kode_RS;
                        exl.Cells[$"B{row}"].Value = x.Nama_RS;
                        exl.Cells[$"C{row}"].Value = x.Bulan;
                        exl.Cells[$"D{row}"].Value = x.Tahun;
                        exl.Cells[$"E{row}"].Value = x.Nama_KabKota;
                        exl.Cells[$"F{row}"].Value = x.Kode_Prov;
                        exl.Cells[$"G{row}"].Value = x.Nomor;
                        exl.Cells[$"H{row}"].Value = x.JenisKegiatan;
                        exl.Cells[$"I{row}"].Value = x.JML;

                        no++;
                        row++;
                    }
                }
            }
            else if (_config == "RL 5.3 10_Besar Penyakit Rawat Inap")
            {
                var no = 1;
                var row = 2;
                using (var s = new SIMEntities())
                {
                    var dt = s.RL_5_3(_fromdate, _todate).ToList();
                    foreach (var x in dt)
                    {
                        //Kode_Prov	Nama_KabKota	Kode_RS	Nama_RS	Bulan	Tahun	Nomor	KodeICD	Deskripsi	Keluar_Hidup_L	Keluar_Hidup_P	Keluar_Mati_L	Keluar_Mati_P	Total_All
                       
                        exl.Cells[$"A{row}"].Value = x.Kode_Prov;
                        exl.Cells[$"B{row}"].Value = x.Nama_KabKota;
                        exl.Cells[$"C{row}"].Value = x.Kode_RS;
                        exl.Cells[$"D{row}"].Value = x.Nama_RS;
                        exl.Cells[$"E{row}"].Value = x.Bulan;
                        exl.Cells[$"F{row}"].Value = x.Tahun;
                        exl.Cells[$"G{row}"].Value = x.Nomor;
                        exl.Cells[$"H{row}"].Value = x.KodeICD;
                        exl.Cells[$"I{row}"].Value = x.Deskripsi;
                        exl.Cells[$"J{row}"].Value = x.Keluar_Hidup_L;
                        exl.Cells[$"K{row}"].Value = x.Keluar_Hidup_P;
                        exl.Cells[$"L{row}"].Value = x.Keluar_Mati_L;
                        exl.Cells[$"M{row}"].Value = x.Keluar_Mati_P;
                        exl.Cells[$"N{row}"].Value = x.Total_All;

                        no++;
                        row++;
                    }
                }
            }
            else if (_config == "RL 5.4 10_Besar Penyakit Rawat Jalan")
            {
                var no = 1;
                var row = 2;
                using (var s = new SIMEntities())
                {
                    var dt = s.RL_5_4(_fromdate, _todate).ToList();
                    foreach (var x in dt)
                    {
                        exl.Cells[$"A{row}"].Value = x.Kode_Prov;
                        exl.Cells[$"B{row}"].Value = x.Nama_KabKota;
                        exl.Cells[$"C{row}"].Value = x.Kode_RS;
                        exl.Cells[$"D{row}"].Value = x.Nama_RS;
                        exl.Cells[$"E{row}"].Value = x.Bulan;
                        exl.Cells[$"F{row}"].Value = x.Tahun;
                        exl.Cells[$"G{row}"].Value = x.Nomor;
                        exl.Cells[$"H{row}"].Value = x.KodeICD;
                        exl.Cells[$"I{row}"].Value = x.Deskripsi;
                        exl.Cells[$"J{row}"].Value = x.Kasus_Baru_L;
                        exl.Cells[$"K{row}"].Value = x.Kasus_Baru_P;
                        exl.Cells[$"L{row}"].Value = x.Kasus_Baru_Total;
                        exl.Cells[$"M{row}"].Value = x.JML_Kunjungan;

                        no++;
                        row++;
                    }
                }
            }
            return exl;
        }

        public List<ExcelInfoViewModel> declareReport()
        {
            var m = new List<ExcelInfoViewModel>()
            {
                new ExcelInfoViewModel()
                {
                    param = "RL 5.1_Pengunjung SIRS",
                    title = $"RL 5.1_Pengunjung SIRS - {_fromdate.ToString("dd-MM-yyyy")} - {_todate.ToString("dd-MM-yyyy")}",
                    filename = "RL 5.1_Pengunjung SIRS.xlsx",
                    worksheet = "Data",
                    report_init = "",
                },
                new ExcelInfoViewModel()
                {
                    param = "RL 5.2_Kunjungan Rawat Jalan",
                    title = $"RL 5.2_Kunjungan Rawat Jalan - {_fromdate.ToString("dd-MM-yyyy")} - {_todate.ToString("dd-MM-yyyy")}",
                    filename = "RL 5.2_Kunjungan Rawat Jalan.xlsx",
                    worksheet = "Data",
                    report_init = "",
                },
                new ExcelInfoViewModel()
                {
                    param = "RL 5.3 10_Besar Penyakit Rawat Inap",
                    title = $"RL 5.3 10_Besar Penyakit Rawat Inap - {_fromdate.ToString("dd-MM-yyyy")} - {_todate.ToString("dd-MM-yyyy")}",
                    filename = "RL 5.3 10_Besar Penyakit Rawat Inap.xlsx",
                    worksheet = "Data",
                    report_init = "",
                },
                new ExcelInfoViewModel()
                {
                    param = "RL 5.4 10_Besar Penyakit Rawat Jalan",
                    title = $"RL 5.4 10_Besar Penyakit Rawat Jalan.xls - {_fromdate.ToString("dd-MM-yyyy")} - {_todate.ToString("dd-MM-yyyy")}",
                    filename = "RL 5.4 10_Besar Penyakit Rawat Jalan.xlsx",
                    worksheet = "Data",

RekamMedik/Views/ReportExcel/Index.cshtml
@using RekamMedik.Helper
@using RekamMedik.Models
@using Newtonsoft.Json
@{
    ViewBag.Title = "Report";
    ViewBag.breadcrumb = new List<SelectListItem>()
{
    new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}
@model ReportRLHelperViewModel

<style>
    .panel-flat > .panel-heading {
        padding-top: 10px !important;
        padding-bottom: 10px !important;
        background-color: #fff;
    }
</style>

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">@Model.Name</h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
        <a class="heading-elements-toggle"><i class="icon-menu"></i></a>
    </div>

    <table class="table table-bordered">
        <tbody>
            @if (Model != null)
            {
                if (Model.RL_List != null)
                {
                    foreach (var x in Model.RL_List)
                    {
                        <tr>
                            <td style="width:80px;"><button onclick='openmodalreportExls("@x.param")' type="button" class="btn btn-success btn-block btn-xs"><i class="icon icon-printer"></i></button></td>
                            <td>@x.param</td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
    <div class="panel-footer">&nbsp;</div>
</div>


<div id="modalreportxls" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Report Excel</h4>
            </div>
            <form id="formprint">
                <div class="modal-body">
                    <div class="form-horizontal">
                        <input type="hidden" name="filenamexls" id="filenamexls" value="">
                        <div class="form-group hidden" id="p_fromdatexls">
                            <label class="control-label col-md-3">Dari Tanggal</label>
                            <div class="col-md-9">
                                <input class="form-control param" type="date" name="fromdatexls" id="fromdatexls" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                            </div>
                        </div>
                        <div class="form-group hidden" id="p_todatexls">
                            <label class="control-label col-md-3">Sampai Tanggal</label>
                            <div class="col-md-9">
                                <input class="form-control param" type="date" name="todatexls" id="todatexls" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-success" onclick="modalprintonExportExcel(event)"><i class="glyphicon glyphicon-download position-left"></i> Download Excel</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function openmodalreportExls(name) {
        var filename = $("#filenamexls");
        var fromd = $("#p_fromdatexls");
        var tod = $("#p_todatexls");

        @if (Model != null)
            {
                if (Model.RL_List != null)
                {
                    foreach (var x in Model.RL_List)
                    {
                    <Text>
                        if (name == "@x.param") {
                            filename.val(name);
                            fromd.removeClass("hidden");
                            tod.removeClass("hidden");
                        }
                    </Text>
                    }
				}
			}

        $("#modalreportxls").modal("show");
    }

    function modalprintonExportExcel(e) {

        e.preventDefault();
        var filename = $("#filenamexls");
        var fromd = $("#fromdatexls");
        var tod = $("#todatexls");
        var url = "@Url.Action("DownloadReport", "ReportExcel")";

        url = url + "?name_xls=" + filename.val() + "&fromdate=" + fromd.val() + "&todate=" + tod.val();

        $("#modalreportxls").modal("hide");
        window.open(url, '_blank');
    }
</script>